### ISSUE TITLE
Compiler warnings printed to stderr

### ISSUE THREAD

**Issue by b-mueller** [b-mueller/sabre#11]
Sabre prints compiler warnings in some cases. [BecToken](https://github.com/SmartContractSecurity/SWC-registry/blob/master/test_cases/solidity/real_world_samples/BECToken/BECToken.sol) for example:

```
$ sabre BECToken/BECToken.sol 
(node:14221) V8: soljson-v0.4.16+commit.d7661dd9.js:3 Invalid asm.js: Invalid member of stdlib
```

Note that the analysis still completes successfully.

## Expected Behaivour

Hide those warnings from the user as they aren't relevant for the outcome of the analysis.

**Comment by eswarasai** [comment]
@b-mueller -- I don't see the compiler warnings on latest `master` for the above contract. Can you confirm the same on your end?

Probably it can be because of different `node`, `solc` versions as well. I'm using `node@10.15.3` and `solc@0.5.5`

**Comment by b-mueller** [comment]
I'm running:

```
Node v11.11.0
solc@0.5.5
```

I'm getting the warning for almost every contract.

**Comment by b-mueller** [comment]
Hmm yeah I stopped getting those now :)
