### ISSUE TITLE
Issues reported for compiler gen'd code

### ISSUE THREAD

**Issue by JoranHonig** [b-mueller/sabre#32]
If the mythx api returns an issue with a sourcemap like "x:x:-1" then this indicates an issue in compiler generated code. 

Currently it seems like this case isn't treated in sabre

**Comment by eswarasai** [comment]
@JoranHonig -- Can you please provide a sample contract with which we can reproduce this error, so that we'd be able to debug it and fix the root cause? Thanks :)

**Comment by b-mueller** [comment]
@JoranHonig can we get a sample for this?

**Comment by Skyge** [comment]
@JoranHonig Have you solved your problem?

**Comment by JoranHonig** [comment]
@Skyge I've sent a dm to @b-mueller with a sample contract

**Comment by Skyge** [comment]
@JoranHonig OK, if you paste it at here, whoever see it will have a try, but you send a dm to `mueller`, maybe only he can help. lol.

**Comment by b-mueller** [comment]
This was resolved a while ago.
