### ISSUE TITLE
Source map does not resolve correctly for imported vulnerable contracts

### ISSUE THREAD

**Issue by cleanunicorn** [b-mueller/sabre#40]
We have a 2 contract setup, in which the main contract inherits a vulnerable contract:

**vulnerableImport.sol**
```solidity
pragma solidity 0.5.0;

import "./imported.sol";

contract C is Imported {}
```

**imported.sol**
```solidity
pragma solidity 0.5.0;

contract Imported {
    function f() public {
        selfdestruct(msg.sender);
    }
}
```

Scanning finds the correct `selfdestruct` problem:
```sh-session
$ sabre ./vulnerableImport.sol
✔ Compiled with solc v0.5.0 successfully
[    ] Analyzing C(node:30670) V8: :3 Invalid asm.js: Invalid member of stdlib

./vulnerableImport.sol
  6:2  error  The contract can be killed by anyone  https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-106

✖ 1 problem (1 error, 0 warnings)
```

However the source mapping does not point to the correct line number. Reported location is `6:2` but line 6 does not exist in the **vulnerableImport.sol** file.

**Observation**
Doing a few more tests I found an interesting behavior. Adding an extra empty line in the vulnerable contract (before the vulnerable code) will increase `6:2` to `6:3`.

**Comment by Skyge** [comment]
Yeah, it looks like there is something wrong with it, I will try to find out the reason and fix it If no one has started to solve this problem yet.

**Comment by eswarasai** [comment]
@cleanunicorn -- Thanks for the example. I'll take a quick look at it and see how I can resolve the source map issue. The problem with imports and their source map linking is something that I haven't debugged yet. Unfortunately `solc` doesn't support resolving imports out of the box. So we're handling it within `sabre`, hence all such issues 😅

**Comment by cleanunicorn** [comment]
I have exactly the same problem in mythos ☺
