### ISSUE TITLE
Bad data in analysis-request JSON

### ISSUE THREAD

**Issue by sjukeshov** [b-mueller/sabre#43]
I tried Sabre with open source contract
https://github.com/cryptocopycats/awesome-cryptokitties/blob/master/contracts/ERC721.sol
which failed like:
```
sabre contracts/ERC721.sol 
Bad data in analysis-request JSON:
In contract ERC721:
* field "bytecode" is not allowed to be empty
* field "bytecode" with value "" fails to match the required pattern: /^(0x)?([0-9a-fA-F]{2})+$/
* field "deployedBytecode" is not allowed to be empty
* field "deployedBytecode" with value "" fails to match the required pattern: /^(0x)?([0-9a-fA-F]{2})+$/
* field "sourceMap" is not allowed to be empty
* field "deployedSourceMap" is not allowed to be empty
```

**Comment by eswarasai** [comment]
@sjukeshov -- I just tried to debug the issue. I'm able to see `abi` and `ast` for this contract but somehow the `evm` is kind of empty, hence the error is thrown while trying to generate report. Any idea why this would happen?

```
 evm:
            { assembly: '',
              bytecode:
               { linkReferences: {}, object: '', opcodes: '', sourceMap: '' },
              deployedBytecode:
               { linkReferences: {}, object: '', opcodes: '', sourceMap: '' },
              gasEstimates: null,
              legacyAssembly: null,
              methodIdentifiers:
               { 'approve(address,uint256)': '095ea7b3',
                 'balanceOf(address)': '70a08231',
                 'ownerOf(uint256)': '6352211e',
                 'supportsInterface(bytes4)': '01ffc9a7',
                 'totalSupply()': '18160ddd',
                 'transfer(address,uint256)': 'a9059cbb',
                 'transferFrom(address,address,uint256)': '23b872dd' } },
```

**Comment by sjukeshov** [comment]
I have no idea to be honest. Just found out this project and that was first contract I tried

**Comment by eswarasai** [comment]
@sjukeshov -- Yeah, that's really weird. I'll see what could be the issue. But please feel free to try `sabre` with other contracts and let us know in case you find any issues. It's helpful to know the failing cases to debug and improve the tool :)

**Comment by b-mueller** [comment]
It's because the contract is only an interface.

**Comment by eswarasai** [comment]
@b-mueller -- So what should be the expected behaviour in such scenarios?

**Comment by b-mueller** [comment]
I'd say display an error message like "Compiling the Solidity code did not return any bytecode. Note that abstract contracts cannot be analyzed.".
