### ISSUE TITLE
Error in regular expression

### ISSUE THREAD

**Issue by sobolev-igor** [b-mueller/sabre#45]
When I try to scan my contracts I get the following error:
```
SyntaxError: Invalid regular expression: /(?<line>\d+):(?<col>\d+):(?<source>\d+)/: Invalid group
```

It raises in lib/helpers.js, line 131

So, I had to change this line into 

```
const sourceMapRegex = /(\d+):(\d+):(\d+)/g;
```

My node version is v8.10.0

Moreover, there is one more problem: 
The numbers of lines are incorrect in my scan. I suppose it is because of multi-line comments and NatSpec comments (ones starting with /** ).

**Comment by b-mueller** [comment]
Hey @sobolev-igor, can you share the contract you are analyzing?

**Comment by sobolev-igor** [comment]
I've just figured out that problem is in special symbols in contract's comments.

```
pragma solidity 0.5.7;

// 추가
//████████╗██████╗  ██████╗ ███╗

contract A {
    //this line triggers MythX pattern
    uint[] public data;
    uint data2;
    uint data3;
    uint data4;
    uint data5;
    uint data6;
    uint data7;
}
```

Removing first two comments fixes the second problem, but the first one still remains.

**Comment by daniyarchambylov** [comment]
@b-mueller I'm getting same error with MetaCoin. Sabre version `sabre-mythx@0.4.5`

**Comment by blitz-1306** [comment]
@b-mueller this may be **node.js** version problem. I got this error on `v8.11.4`.

**Comment by b-mueller** [comment]
Yes, looks like named capture groups were introduced only recently.

Should we simplify the regex for backwards compatibility?

**Comment by blitz-1306** [comment]
@b-mueller as I see, two options available:
- Simplify regex - will be user-oriented approach.
- Specify minimal required NodeJs version for current regex to work - will be at least informative, so users will not suffer and will not create issues here.

I would be nice if regex can be simplified. If not, then second option should be considered.

**Comment by b-mueller** [comment]
@blitz-1306 @sobolev-igor this should be fixed in latest master, can you please verify.

```
$  npm install git+https://github.com/b-mueller/sabre
```

**Comment by sobolev-igor** [comment]
@b-mueller works correctly on my computer, thanks! 

however, special symbols still break line numbers (don't think it's important so much)

**Comment by blitz-1306** [comment]
@b-mueller Confirm that regex crash no longer occurs - report is produced.
