### ISSUE TITLE
Optimize download compiler version.

### ISSUE THREAD

**Issue by Skyge** [b-mueller/sabre#49]
At the current version, I notice that, in the `package.json`, we use `solc` dependency to compile the contract,
```
"dependencies": {
    "solc": "^0.5.7",
  },
```
so if we specify version at here, we should always update it manually when the `solc` version becomes `0.5.8`, `0.5.9` and so on. So I think we should download the required version automatically.

**Comment by b-mueller** [comment]
Closed by #50.
