### ISSUE TITLE
TypeError: Cannot read property '3' of null

### ISSUE THREAD

**Issue by daniyarchambylov** [b-mueller/sabre#57]
Running arbitrary_location_write_simple.sol from https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-101
```
$ sabre contracts/arbitrary_location_write_simple.sol
✔ Compiled with solc v0.4.25 successfully
TypeError: Cannot read property '3' of null
```

**Comment by eswarasai** [comment]
I haven't handled the sourceIndex to have `-1` value for compiler generated code. Hence the error. Just pushed a fix to this as well :)
