### ISSUE TITLE
Add a batch analysis mode

### ISSUE THREAD

**Issue by b-mueller** [b-mueller/sabre#87]
## Description

Add a batch analysis mode that scans multiple Solidity files and produces a combined report. 

## Implementation

I'm not 100% sure about how to best explore this feature to users. Some options are:

1. Accept multiple filename/contract, i.e.

```
$ sabre <file1.sol>[:contractName1] <file2.sol>[:contractName2]
```

This would allow the user to do bash stuff like `find ./ -name "*.sol" | xargs sabre` or save the a Sabre command line as a shell script to repeatedly analysis a whole repo.

2. Accept an input directory, traverse the directory recursively to find and analyze all .sol files.

This would be convenient but would cost the user some control. One question is how we would handle .sol files containing multiple contract classes. We'd probably also need a feature to exclude specific contracts etc.

**Comment by maurelian** [comment]
I prefer the first option, it would allow doing things like `sabre contracts/*.sol` which is pretty typical.

**Comment by blitz-1306** [comment]
Should we preserve polling delays, or should we reconsider this logic for **batch** mode?
