### ISSUE TITLE
Allow for analysis of complex contracts

### ISSUE THREAD

**Issue by RyRy79261** [b-mueller/sabre#9]
```File import callback not supported```

Contracts with imported files cant be analyzed, this severely limits the utility of this tool.

**Comment by b-mueller** [comment]
Hmm, that's weird. Imports shouldn't be an issue assuming that solc-js can resolve them. I'll look into it!

**Comment by b-mueller** [comment]
@RyRy79261 can you try again with sabre-mythx 0.1.0?

**Comment by b-mueller** [comment]
Imports should be fully supported as of sabre-mythx 0.1.2 so I'm closing this.
